language: php

php:
  - 7.2
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - php vendor/phpunit/phpunit/phpunit --coverage-text
  - php vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR2 -n ./src
