language: php

php:
  - 7.2
  - 7.1

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 -n ./src
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
